### ISSUE TITLE
suggest部分の選択欄を吹き出しに変更

### ISSUE THREAD

**Issue by mori-harmo** [gochipon/DIS23-b#21]
## イメージ図
![image](https://github.com/gochipon/DIS23-b/assets/64515173/23d0805a-378a-49f9-97ab-ed7bb03581e2)

**Comment by Shun-Takashige** [comment]
- https://codesandbox.io/s/react-insert-context-menu-value-into-textarea-rhq5wq?file=/src/App.tsx
- 上のプロジェクトをtextareaではない場所で使えるか…？

**Comment by Shun-Takashige** [comment]
- これとかも使えそう
- https://mui.com/material-ui/react-popper/
